GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/

###

GET http://localhost:3003/api/blogs/6369468cb42fd4982fc048ba

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "A second blog by the first user",
    "author": "Mateo Astudillo",
    "url": "www.2ndBlog.com",
    "likes": "11"
}

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdGVvYXAwMCIsImlkIjoiNjNhNDg2YmE0NjYwZDJiYTNiOWE4MGIyIiwiaWF0IjoxNjcxNzI4MTI2fQ.wsHAH-YcitmPL4kBoESkirQhZ4-0kWZStwS-PrNn-5M

{
    "title": "Blog by user, with token authentication",
    "author": "Mateo Astudillo",
    "url": "www.blogAuthorized.com",
    "likes": "5"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "mateoap00",
    "name": "Mateo Astudillo",
    "password": "astudillo"
}

###

POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "mateoap00",
    "password": "astudillo"
}

