GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/

###

GET http://localhost:3003/api/blogs/6369468cb42fd4982fc048ba

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "A second blog by the first user",
    "author": "Mateo Astudillo",
    "url": "www.2ndBlog.com",
    "likes": "11"
}

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdGVvYXAwMCIsImlkIjoiNjNhMzVlMDI5MWE1MmNhNjM2NGU1ZTEyIiwiaWF0IjoxNjcxNjcwNjY1fQ.q9NPmBzP1Nm-5ixuS1a_yZlEYV_CZPJmAtVT8nMolOQ

{
    "title": "4th Blog by user, with token authentication",
    "author": "mateoap00",
    "url": "www.blog2nd.com",
    "likes": "15"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "mateoap00",
    "name": "Mateo Astudillo",
    "password": "astudillo"
}

###

POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "mateoap00",
    "password": "astudillo"
}

