GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/

###

GET http://localhost:3003/api/blogs/6369468cb42fd4982fc048ba

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "blog 5",
    "author": "author 5",
    "url": "www.blog5.com",
    "likes": "8"
}